import json
import os
import re

def sanitize_filename(name):
    # Remove characters that are illegal in Windows filenames
    return re.sub(r'[<>:"/\\|?*]', '_', name)

def generate_vault(json_path, output_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    nodes = data.get('nodes', [])
    links = data.get('links', [])

    # Map node IDs to node labels for linking
    id_to_label = {node['id']: node['label'] for node in nodes}
    
    # Map node labels to filenames
    label_to_filename = {node['label']: f"{sanitize_filename(node['label'])}.md" for node in nodes}

    # Group links by source node
    node_links = {}
    for link in links:
        source_id = link.get('_src') or link.get('source')
        target_id = link.get('_tgt') or link.get('target')
        relation = link.get('relation', 'related')
        
        if source_id not in node_links:
            node_links[source_id] = []
        node_links[source_id].append((target_id, relation))

    # Create individual node files
    for node in nodes:
        label = node['label']
        filename = label_to_filename[label]
        filepath = os.path.join(output_dir, filename)
        
        content = []
        content.append("---")
        content.append(f"id: {node['id']}")
        content.append(f"file_type: {node.get('file_type', 'unknown')}")
        content.append(f"source_file: {node.get('source_file', 'unknown')}")
        content.append(f"community: {node.get('community', 'unknown')}")
        content.append("---")
        content.append(f"\n# {label}\n")
        
        if 'source_file' in node:
            content.append(f"**Source File:** `{node['source_file']}`")
        if 'source_location' in node:
            content.append(f"**Location:** `{node['source_location']}`")
            
        content.append("\n## Relationships\n")
        
        links_for_node = node_links.get(node['id'], [])
        if links_for_node:
            for target_id, relation in links_for_node:
                target_label = id_to_label.get(target_id, target_id)
                content.append(f"- **{relation}**: [[{target_label}]]")
        else:
            content.append("No outgoing relationships detected.")
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(content))

    # Group nodes by community
    communities = {}
    for node in nodes:
        comm = node.get('community', 'Unknown')
        if comm not in communities:
            communities[comm] = []
        communities[comm].append(node)

    # Create Community Index
    community_index_path = os.path.join(output_dir, "_Community Map.md")
    comm_content = ["# Community Map\n"]
    for comm, comm_nodes in sorted(communities.items(), key=lambda x: str(x[0])):
        comm_content.append(f"## Community {comm}")
        for node in comm_nodes:
            comm_content.append(f"- [[{node['label']}]]")
        comm_content.append("")
    
    with open(community_index_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(comm_content))

    # Create Start Here
    start_here_path = os.path.join(output_dir, "_Start Here.md")
    start_content = [
        "# India AQI Dashboard - Knowledge Graph",
        "\nWelcome to the Obsidian vault for the India AQI Dashboard project.",
        "\n## Exploration Path",
        "- [[_Community Map|View Communities]] - Explore the system by functional modules.",
        "- [[India AQI Dashboard]] - The central hub of the project.",
        "\n## Statistics",
        f"- Total Nodes: {len(nodes)}",
        f"- Detected Communities: {len(communities)}",
        "\n---",
        "\nGenerated by Antigravity using Graphify output."
    ]
    with open(start_here_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(start_content))

    print(f"Generated {len(nodes)} notes, Community Map, and Start Here in {output_dir}")

if __name__ == "__main__":
    json_path = r"c:\Users\Amol\Desktop\Antigravity\AQI project\graphify-out\graph.json"
    output_dir = r"c:\Users\Amol\Desktop\Antigravity\AQI project\obsidian-vault"
    generate_vault(json_path, output_dir)
